// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvTPEWx-3JQpnoqB6vMcZjthH6C_eNoM',
    appId: '1:919929134018:web:379b866050ea7ebf4b545b',
    messagingSenderId: '919929134018',
    projectId: 'package-scanner-20d1d',
    authDomain: 'package-scanner-20d1d.firebaseapp.com',
    storageBucket: 'package-scanner-20d1d.firebasestorage.app',
    measurementId: 'G-YEJQKVX0RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoFJHqIWsRUGIOOEYsOu4YOu25Buc_N0',
    appId: '1:919929134018:android:de2b739390a042494b545b',
    messagingSenderId: '919929134018',
    projectId: 'package-scanner-20d1d',
    storageBucket: 'package-scanner-20d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFvUzQTT9BPfzQV6gwsRU_8n5r3MZA_4',
    appId: '1:919929134018:ios:b74af8095947c6434b545b',
    messagingSenderId: '919929134018',
    projectId: 'package-scanner-20d1d',
    storageBucket: 'package-scanner-20d1d.firebasestorage.app',
    iosBundleId: 'com.example.sihProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfFvUzQTT9BPfzQV6gwsRU_8n5r3MZA_4',
    appId: '1:919929134018:ios:b74af8095947c6434b545b',
    messagingSenderId: '919929134018',
    projectId: 'package-scanner-20d1d',
    storageBucket: 'package-scanner-20d1d.firebasestorage.app',
    iosBundleId: 'com.example.sihProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdvTPEWx-3JQpnoqB6vMcZjthH6C_eNoM',
    appId: '1:919929134018:web:c3b701ce2814ce0e4b545b',
    messagingSenderId: '919929134018',
    projectId: 'package-scanner-20d1d',
    authDomain: 'package-scanner-20d1d.firebaseapp.com',
    storageBucket: 'package-scanner-20d1d.firebasestorage.app',
    measurementId: 'G-PK69L53TKW',
  );
}
